use `examerdb`;

#初始化全局账号字段
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `modifier`) VALUES ('帐号', 'account', '1', '1', '1', '0', '1', '0', 'system', '1', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `modifier`) VALUES ('密码', 'password', '1', '0', '0', '0', '2', '0', 'system', '1', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `modifier`) VALUES ('姓名', 'name', '1', '0', '0', '0', '3', '0', 'system', '1', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `modifier`) VALUES ('邮箱', 'email', '1', '0', '0', '0', '4', '0', 'system', '1', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `modifier`) VALUES ('手机', 'mobile', '1', '0', '1', '0', '5', '0', 'system', '1', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `select_value`, `modifier`) VALUES ('性别', 'gender', '0', '0', '0', '0', '6', '0', 'system', '3', '男,女', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `select_value`, `modifier`) VALUES ('最高学历', 'high_education', '0', '0', '0', '0', '7', '0', 'system', '3', '初中及以下,中技,中专,高中,大专,本科,硕士,MBA&EMBA,博士及以上', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `modifier`) VALUES ('身份证号', 'identity_num', '0', '0', '0', '0', '8', '0', 'system', '1', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `modifier`) VALUES ('出生日期', 'birthday', '0', '0', '0', '0', '9', '0', 'system', '2', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `select_value`, `modifier`) VALUES ('工作年限', 'work_years', '0', '0', '0', '0', '10', '0', 'system', '3', '学生,2年以内,3-5年,6-8年,9-10年,11-15年,16年以上', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `select_value`, `modifier`) VALUES ('行业', 'industry_name', '0', '0', '0', '0', '11', '0', 'system', '3', '互联网/游戏/软件,电子/通信/硬件,房地产/建筑,物业,银行,保险,基金/证劵/期货/投资,互联网金融,快消,鞋服,零售,机械/制造,汽车,专业服务/教育/培训,餐饮/酒店/生活服务,制药/医疗,广告/媒体/文化,交通/物流,贸易/进出口,能源/化工/环保,多元化集团,政府/事业单位,其他', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `select_value`, `modifier`) VALUES ('政治面貌', 'political_status', '0', '0', '0', '0', '12', '0', 'system', '3', '群众,共青团员,共产党员,其他民主党派', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `modifier`) VALUES ('部门', 'dept_name', '0', '0', '0', '0', '13', '0', 'system', '1', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `modifier`) VALUES ('职位', 'position', '0', '0', '0', '0', '14', '0', 'system', '1', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `modifier`) VALUES ('毕业院校', 'school', '0', '0', '0', '0', '15', '0', 'system', '1', 'system');
INSERT INTO `examerdb`.`t_user_show_field` (`field_name`, `field_key`, `isshow`, `ismandatory`, `isunique`, `isextension`, `sortnum`, `company_id`, `creater`, `type`, `modifier`) VALUES ('专业', 'profression', '0', '0', '0', '0', '16', '0', 'system', '1', 'system');

#初始化短信模板
INSERT INTO `examerdb`.`t_notify_template`(company_id,name,content,subject,sign,type,method,status,whether_default,creator,created_date,modifier,modified_date) VALUES ( '0', '考试邮件通知 [中]（系统模板）', '<p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">尊敬的$$姓名$$ $$先生/女士$$</span><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">：</span></p><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">您好！诚邀您参加线上考试。您有</span><a style=\"font-family: 宋体, SimSun; font-size: 16px; text-decoration: none;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">$$任务数量$$</span></a><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">个考试任务待完成。</span></p><p style=\"line-height: 2em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\"><strong>注意事项：</strong></span></p><ul class=\" list-paddingleft-2\" style=\"list-style-type: disc;\"><li><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">考试均有时间要求，请自行安排好时间进行考试。您可提前10分钟登录系统并完善个人信息。</span></p></li><li><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">考试过程中：</span></p><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">情况一，在“限时考试”中，如退出系统或退出当前考试任务，倒计时不暂停，请保证连续答题时间；</span></p><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">情况二，在“统一时点交卷考试”中，如退出系统或退出当前考试任务，在“答题入口关闭时间”后将被强制交卷且不可再进入该任务。</span></p></li><li><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">请您在网络状况良好且安静的环境下完成考卷填写。若遇到其他因素干扰，请确保尽快回到答题界面继续答题。</span></p></li><li><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">本次考试支持电脑端和手机端答题。为实现更流畅答题，建议电脑端使用IE9以上版本浏览器。</span></p></li></ul><p style=\"line-height: 2em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\"><strong>操作步骤：</strong></span></p><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">1、请点击链接：$$考试地址$$</span></p><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">2、使用个人帐号登陆：$$帐号$$ ，密码：$$密码$$</span></p><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">3、完成帐号内所有考试填答</span></p><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">4、考试结束后，页面会显示“已完成”，系统将保存答题结果。客观题由系统自动计分，主观题由评卷人评卷。</span></p><p style=\"line-height: 2em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">如在考试过程中遇到问题，请咨询网页上的QQ客服，或拨打倍智服务热线400-012-5066（服务时间：周一至周五，9:00-18:00</span></p><p><br/></p>', '考试通知邮件', '', '0', '0', '1', '0', 'system', '2017-01-07 14:19:18', 'system', '2017-01-07 15:13:35');
INSERT INTO `examerdb`.`t_notify_template`(company_id,name,content,subject,sign,type,method,status,whether_default,creator,created_date,modifier,modified_date) VALUES ( '0', '评卷通知[中]（系统模板）', '<p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">尊敬的 $$评卷人姓名$$ 先生/女士：</span></p><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">您好！诚邀您进行线上评卷。您有</span><a style=\"font-family: 宋体, SimSun; font-size: 16px; text-decoration: none;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">$$任务数量$$</span></a><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">个评卷任务待完成。</span></p><p style=\"line-height: 1.75em;\"><span style=\"font-size: 16px;\"><strong><span style=\"font-size: 16px; font-family: 宋体, SimSun;\">操作步骤：</span></strong></span></p><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">1、请点击链接：$$评卷地址$$</span></p><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">2、使用个人帐号登陆：$$帐号$$ ，密码：$$密码$$</span></p><p style=\"line-height: 1.5em;\"><span style=\"font-family: 宋体, SimSun; font-size: 16px;\">如在评卷过程中遇到问题，请咨询网页上的QQ客服，或拨打倍智服务热线400-012-5066（服务时间：周一至周五，9:00-18:00）</span></p><p><br/></p><p><br/></p>', '评卷通知邮件', '', '0', '0', '1', '0', 'system', '2017-01-07 14:58:33', 'system', '2017-01-07 15:03:43');
INSERT INTO `examerdb`.`t_notify_template`(company_id,name,content,subject,sign,type,method,status,whether_default,creator,created_date,modifier,modified_date) VALUES ( '0', '考试短信通知 [中]（系统模板）', '您好！您有$$任务数量$$个考试待完成。请点击：$$考试地址$$ ，用帐号：$$帐号$$ ，密码：$$密码$$登录后根据要求作答试卷，谢谢！', null, null, '0', '1', '1', '0', 'system', '2017-01-07 15:21:51', 'system', '2017-01-07 15:24:30');
INSERT INTO `examerdb`.`t_notify_template`(company_id,name,content,subject,sign,type,method,status,whether_default,creator,created_date,modifier,modified_date) VALUES ( '0', '评卷通知[中]（系统模板）', '您好！您有$$任务数量$$ 评卷任务待完成。请点击如下链接进行评卷：$$评卷地址$$ ，帐号：$$帐号$$，密码：$$密码$$ 。谢谢！', null, null, '0', '1', '1', '0', 'system', '2017-01-07 15:23:05', 'system', '2017-01-07 15:24:00');

use examerDb;
ALTER TABLE t_exercise
ADD CONSTRAINT exercise_unique_id UNIQUE (user_id,task_id);