#service discovery url
eureka:
   client:
      serviceUrl:
           defaultZone: http://192.168.1.235:29003/eureka/
   instance:
       leaseRenewalIntervalInSeconds: 3
       leaseExpirationDurationInSeconds: 9
spring:
  application:
    name: ms-email
  cloud:
    stream:
      bindings:
        email_input_channel:                   #channelName
             destination: email_mq        #destination，或者可以认为是发布－订阅模型里面的topic
             binder: rabbit_notify_mq
      binders:
        rabbit_notify_mq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.1.158   #rabbitMQ服务器地址
                port: 5672           #rabbitMQ服务器端口
                username: guest
                password: guest
                virtual-host: /

#port
server:
    port: 28003

#datasource
datasource.admin:
  url: jdbc:mysql://192.168.1.242:3306/commonDb?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
  username: bzceshi
  password: 123123x
  driver-class-name: com.mysql.cj.jdbc.Driver
  max-active: 30
  max-idle: 10
  max-wait: 5000
  initial-size: 5
  validation-query: SELECT 1
  type: com.alibaba.druid.pool.DruidDataSource



#druid
druid:
  loginUsername: admin
  loginPassword: admin


logging:
   level:
      com:
         talebase:
                cloud:
                    ms:
                      email:
                          dao: DEBUG