spring:
  redis:
     host: 192.168.1.158
     database: 15
     password:
     port: 6379
     pool:
         max-wait: -1
         max-idle: 8
         min-idle: 1
     timeout: 0
  application:
      name: api-gateway
server:
  port: 29001

ribbon:
    eureka:
      enabled: true
    ConnectTimeout: 15000
    ReadTimeout: 15000

hystrix:
    command:
       default:
         execution:
            timeout:
               enabled: false

zuul:
  host:
     connect-timeout-millis: 15000
     socket-timeout-millis: 1000
  routes:
     osadmin:
        path: /osadmin/**
        serviceId: os-admin
     osproject:
        path: /osproject/**
        serviceId: os-project
     ospaper:
        path: /ospaper/**
        serviceId: os-paper
     osconsume:
        path: /osconsumption/**
        serviceId: os-consumption
     osexamer:
        path: /osexamer/**
        serviceId: os-examer
     oslogin:
        path: /oslogin/**
        serviceId: os-login

eureka:
  client:
    serviceUrl.defaultZone: http://192.168.1.235:29003/eureka/

